/* This file was generated by buildtools/svnrev/svnrev.pl */
/* #define TT_VERSION_STR "5.5.0-dev" check teraterm/common/tt-version.h */
#define GITVERSION "14a15a5b0"
#undef SVNVERSION
#undef TERATERM_RELEASE
#define BRANCH_NAME "main"
